### PR TITLE
Update mediabots_ui.sh

### PR DESCRIPTION
**Pull request by paulwaldmann**
Remove WET code, formatted and added WP-CLI

### CODE REVIEW

**Comment by paulwaldmann** [comment]
Also, just curious why you added all the `sleep` in your script. I mean, the script won't continue to run until the previous executions completed.

**Comment by mediabots** [comment]
Ok

Ohh, those sleeps were made for testing purpose
testing of non interactive coammands. and keep on track ,where every thing functioning well.
I would remove them

Another thing I noticed in your update, that
[ "$wordpress_installation" = 'Y' -o "$wordpress_installation" = 'y' ]

thing would not work
have to pass $wordpress_installation = 'Y' 
I meant with out quote

**Comment by mediabots** [comment]
its ok.
right now,I am testing the script.
After that , I would merge

**Comment by paulwaldmann** [comment]
I did not further look into it; I just added double quote everywhere to prevent word splitting and globbing.

**Comment by mediabots** [comment]
Oh
Then , its ok

**Comment by paulwaldmann** [comment]
Maybe I'm wrong, test it and let me know. Always happy to help!

Perhaps we can collaborate and make more scripts for all kind of applications. Maybe make a monolith in Go, a single binary with a catalog of apps 🤔

**Pull request merged**
